name: ytdwn
description: Android app for downloading content from YouTube.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <3.3.1'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.2
  youtube_explode_dart: ^2.1.0
  simple_loading_dialog: ^0.5.0
  permission_handler: ^11.2.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon3.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/warning.svg
    - assets/icon3.png
    - assets/logo_neon.jpeg
